// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/Cart.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Cart struct {
	CartId               int32    `protobuf:"varint,1,opt,name=cartId,proto3" json:"cartId,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	CreatedDateISO       string   `protobuf:"bytes,3,opt,name=createdDateISO,proto3" json:"createdDateISO,omitempty"`
	LastModifiedDateISO  string   `protobuf:"bytes,4,opt,name=lastModifiedDateISO,proto3" json:"lastModifiedDateISO,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cart) Reset()         { *m = Cart{} }
func (m *Cart) String() string { return proto.CompactTextString(m) }
func (*Cart) ProtoMessage()    {}
func (*Cart) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2f634b6acca8acd, []int{0}
}

func (m *Cart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cart.Unmarshal(m, b)
}
func (m *Cart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cart.Marshal(b, m, deterministic)
}
func (m *Cart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cart.Merge(m, src)
}
func (m *Cart) XXX_Size() int {
	return xxx_messageInfo_Cart.Size(m)
}
func (m *Cart) XXX_DiscardUnknown() {
	xxx_messageInfo_Cart.DiscardUnknown(m)
}

var xxx_messageInfo_Cart proto.InternalMessageInfo

func (m *Cart) GetCartId() int32 {
	if m != nil {
		return m.CartId
	}
	return 0
}

func (m *Cart) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Cart) GetCreatedDateISO() string {
	if m != nil {
		return m.CreatedDateISO
	}
	return ""
}

func (m *Cart) GetLastModifiedDateISO() string {
	if m != nil {
		return m.LastModifiedDateISO
	}
	return ""
}

type CartList struct {
	CartId               int32    `protobuf:"varint,1,opt,name=cartId,proto3" json:"cartId,omitempty"`
	ItemId               int32    `protobuf:"varint,2,opt,name=itemId,proto3" json:"itemId,omitempty"`
	Quantity             int32    `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ItemAddedDateISO     string   `protobuf:"bytes,4,opt,name=itemAddedDateISO,proto3" json:"itemAddedDateISO,omitempty"`
	UnitPrice            float32  `protobuf:"fixed32,5,opt,name=unitPrice,proto3" json:"unitPrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CartList) Reset()         { *m = CartList{} }
func (m *CartList) String() string { return proto.CompactTextString(m) }
func (*CartList) ProtoMessage()    {}
func (*CartList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2f634b6acca8acd, []int{1}
}

func (m *CartList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CartList.Unmarshal(m, b)
}
func (m *CartList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CartList.Marshal(b, m, deterministic)
}
func (m *CartList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CartList.Merge(m, src)
}
func (m *CartList) XXX_Size() int {
	return xxx_messageInfo_CartList.Size(m)
}
func (m *CartList) XXX_DiscardUnknown() {
	xxx_messageInfo_CartList.DiscardUnknown(m)
}

var xxx_messageInfo_CartList proto.InternalMessageInfo

func (m *CartList) GetCartId() int32 {
	if m != nil {
		return m.CartId
	}
	return 0
}

func (m *CartList) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *CartList) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *CartList) GetItemAddedDateISO() string {
	if m != nil {
		return m.ItemAddedDateISO
	}
	return ""
}

func (m *CartList) GetUnitPrice() float32 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

func init() {
	proto.RegisterType((*Cart)(nil), "protobuf.Cart")
	proto.RegisterType((*CartList)(nil), "protobuf.CartList")
}

func init() { proto.RegisterFile("protobuf/Cart.proto", fileDescriptor_f2f634b6acca8acd) }

var fileDescriptor_f2f634b6acca8acd = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x77, 0x4e, 0x2c, 0x2a, 0xd1, 0x03, 0xf3, 0x84, 0x38, 0x60, 0x82,
	0x4a, 0x13, 0x18, 0xb9, 0x58, 0x40, 0x12, 0x42, 0x62, 0x5c, 0x6c, 0xc9, 0x89, 0x45, 0x25, 0x9e,
	0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x50, 0x1e, 0x48, 0xbc, 0xb4, 0x38, 0xb5, 0xc8,
	0x33, 0x45, 0x82, 0x09, 0x22, 0x0e, 0xe1, 0x09, 0xa9, 0x71, 0xf1, 0x25, 0x17, 0xa5, 0x26, 0x96,
	0xa4, 0xa6, 0xb8, 0x24, 0x96, 0xa4, 0x7a, 0x06, 0xfb, 0x4b, 0x30, 0x2b, 0x30, 0x6a, 0x70, 0x06,
	0xa1, 0x89, 0x0a, 0x19, 0x70, 0x09, 0xe7, 0x24, 0x16, 0x97, 0xf8, 0xe6, 0xa7, 0x64, 0xa6, 0x65,
	0x22, 0x14, 0xb3, 0x80, 0x15, 0x63, 0x93, 0x52, 0x5a, 0xc0, 0xc8, 0xc5, 0x01, 0x72, 0x92, 0x4f,
	0x66, 0x31, 0x5e, 0x67, 0x65, 0x96, 0xa4, 0xe6, 0x22, 0x9c, 0x05, 0xe1, 0x09, 0x49, 0x71, 0x71,
	0x14, 0x96, 0x26, 0xe6, 0x95, 0x64, 0x96, 0x54, 0x82, 0x1d, 0xc4, 0x1a, 0x04, 0xe7, 0x0b, 0x69,
	0x71, 0x09, 0x80, 0x54, 0x39, 0xa6, 0xa4, 0xa0, 0xbb, 0x03, 0x43, 0x5c, 0x48, 0x86, 0x8b, 0xb3,
	0x34, 0x2f, 0xb3, 0x24, 0xa0, 0x28, 0x33, 0x39, 0x55, 0x82, 0x55, 0x81, 0x51, 0x83, 0x29, 0x08,
	0x21, 0x60, 0xc4, 0xcb, 0xc5, 0x0d, 0x72, 0x61, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0x6a, 0x12,
	0x1b, 0x38, 0x38, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x16, 0xce, 0x42, 0xfe, 0x6c, 0x01,
	0x00, 0x00,
}
